baseURL = "http://localhost/"
theme = "up-business-theme"
languageCode = "en-us"
title = "J3C"
summaryLength = 20

[params]
title = "J3C"
description = "We specialize in providing services to desing websites, applications, build and maintain business for customers."
images = [ "images/hero-image.png" ]
logo = "arrow-up.png"
location = [
  "3891 Ranchview Dr. Richardson, California 62639",
  "4517 Washington Ave. Manchester, Kentucky 39495"
]
contact = [ "stevenleeloong@gamail.com", "207.555.0119" ]
copyright = "© 2024 J3C All Rights Reserved"

  [params.favicons]
  themeColor = "#FFFFFF"
  backgroundColor = "#FFFFFF"
  faviconColor = "#000000"

  # [params.social]
  # facebook = "longxianwen"
  # twitter = "longxianwen"

[[menus.main]]
name = "Home"
url = "/#hero"
weight = 1

[[menus.main]]
name = "How we work"
url = "/#"
weight = 2

[[menus.main]]
name = "Our team"
url = "/#"
weight = 3

[[menus.main]]
name = "Pricing"
url = "/#"
weight = 4

[[menus.main]]
name = "Blog"
url = "/blog"
weight = 5

[[menus.buttons]]
name = "Book a call"
url = "/#"
weight = 5
pre = "btn btn-primary text-light"

[[menus.footer]]
name = "Home"
url = "/#hero"
weight = 1

[[menus.footer]]
name = "How we work"
url = "/#"
weight = 2

[[menus.footer]]
name = "Our team"
url = "/#"
weight = 3

[[menus.footer]]
name = "Pricing"
url = "/#"
weight = 4

[[menus.footer]]
name = "Blog"
url = "/blog"
weight = 5

[taxonomies]
series = "series"
tags = "tags"
